### ISSUE TITLE
VectorDrawable not work <android 21 in appcompat-v7 25.3.1

### ISSUE THREAD

**Issue by Ubhadiyap** [dandar3/android-support-v7-appcompat#3]
I import all libs as per your instruction. it isn't work on prelollipop android version .

**abc_vector_test.xml** in V7

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportHeight="24.0"
        android:viewportWidth="24.0">
    <path
        android:fillColor="@android:color/white"
        android:pathData="M20,11L7.8,11l5.6,-5.6L12,4l-8,8l8,8l1.4,-1.4L7.8,13L20,13L20,11z"/>
</vector>
```

```
04-13 11:42:45.072: E/AndroidRuntime(29999): FATAL EXCEPTION: main
04-13 11:42:45.072: E/AndroidRuntime(29999): Process: com.example.vrs.collapsingtoolbardemo, PID: 29999
04-13 11:42:45.072: E/AndroidRuntime(29999): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vrs.collapsingtoolbardemo/com.example.vrs.collapsingtoolbardemo.LauncherActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.os.Looper.loop(Looper.java:149)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.ActivityThread.main(ActivityThread.java:5268)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at dalvik.system.NativeStart.main(Native Method)
04-13 11:42:45.072: E/AndroidRuntime(29999): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.content.res.Resources.loadDrawable(Resources.java:2156)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.content.res.Resources.loadDrawable(Resources.java:2075)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.content.res.Resources.getDrawable(Resources.java:706)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at com.example.vrs.collapsingtoolbardemo.LauncherActivity.onCreate(LauncherActivity.java:19)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.Activity.performCreate(Activity.java:5411)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	... 11 more
04-13 11:42:45.072: E/AndroidRuntime(29999): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	at android.content.res.Resources.loadDrawable(Resources.java:2152)
04-13 11:42:45.072: E/AndroidRuntime(29999): 	... 31 more

```

**Comment by dandar3** [comment]
That is the original source indeed, only that if you use `dex2jar` to look into your generated APK contents, `aapt` (Android Asset Packagint Tool, from `ANDROID_SDK\platform\tools\x.y.z\`) will in fact create two versions, one in `res\drawable-v21\abc_vector_test.xml` which is fine and surprise, one in `\res\drawable\abc_vector_test.xml` which is borked and is the one that devices below v21 load:

```<?xml version="1.0" encoding="utf-8"?>
<vector android:height="24.0dip" android:width="24.0dip"
  xmlns:android="http://schemas.android.com/apk/res/android">
    <path />
</vector>
```

The solution is the AAPT's `--no-version-vectors` parameter, problem is that Google's ADT is not maintained anymore so it doesn't support this new feature:
```
   --no-version-vectors
     Do not automatically generate versioned copies of vector XML resources.
```
You can read more about it below:
https://android-developers.googleblog.com/2016/02/android-support-library-232.html

If there is some good news is that is that [Eclipse Andmore](https://projects.eclipse.org/projects/tools.andmore) project does support it.
https://github.com/eclipse/andmore/commit/6a93942dbe148288898b7e45a8f54cb7d6dadcd0

What you can do to prove it works (and I know cause I've done it) is to:
* download a new Eclipse (e.g. 4.6 for Java Developers package), install Andmore plugin (directly from link above or from Help > Eclipse Marketplace > search for Andmore)
* copy your current workspace as it is into a new folder and open this new location with the new Eclipse Andmore installation (so it doesn't affect your current Eclipse ADT based workspace, you'll see why later);
* right click each project in the workspace and choose `Configure` > `Convert ADT project` (this will change `.classpath` and `.project` from `com.android.ide` package to `org.eclipse.andmore`);
* right click your app project and go to `Properties` > `Android` > check the box for Other options: `--no-version-vectors`.
* clean your app project and deploy again.

This parameter will make AAPT keep the original file instead of creating two separate copies of which one is broken.

I know it sounds like a lot of work but's not that much really - I meant to write a blog article on how to switch from Eclipse ADT to Eclipse Andmore and this is more a reason for it. Hope the directions here will help for now.

**Comment by dandar3** [comment]
No response since, closing the issue.

**Comment by dandar3** [comment]
I wrote a blog post about a new solution for Eclipse ADT if anyone else is interested, more details here:
https://dandar3.blogspot.com/2018/01/appcompat-runtime-error.html

New AAPT wrapper project here:
https://github.com/dandar3/android-aapt-wrapper

**Comment by mortalis13** [comment]
Thanks. It works finally. I had to struggle with some config problems first. It seems that both ADT and Andmore don't coexist. Then when you Cofigure projects for Andmore you should reconfigure libs dependencies (remove/add libs in the Android-Library section).

By the way, after I load appcompat module with its dependencies from the SVN I then added each .jar form the 'libs' subfolders to the Build Path and to the Export so that the main app compiles fine.
Is that the right way?

It seems easier to add all projects to the main app Build Path (in the projects tab). It compiles in this case but doesn't build/run the final APK.

**Comment by dandar3** [comment]
@mortalis13 
They recommend to have separate Eclipse instalations for ADT and for Andmore, yes.
> It is not recommended to have Andmore and ADT installed into the same instance of eclipse, but you can open the same workspace with Andmore and then convert the projects so they are usable by Andmore

You can select multiple ADT library projects (e.g. Android Support Library) in your workspace > right-click > `Configure` > `Convert to Andmore project`
https://github.com/eclipse/andmore/wiki/FAQ

After downloading / importing `android-support-v7-appcompat` (recommending the Team Project set method as it will bring all dependecies as well), ALL you have to do is add `android-support-v7-appcompat` as a dependency in your app project > `Properties` > `Android` > `Library` section, see the screenshot in [this post](https://dandar3.blogspot.com/2018/01/appcompat-runtime-error.html). 

That's all you need to do, ADT / Andmore will compile your app project bringing all dependencies over into your APK, that is because they are already linked in cascade the same way as above - you don't need to muck about with jars and classpaths.

I've used the `Java Build Path` > `Projects` on the library projects cause I wanted them to complain and fail if you are importing them one by one instead of the Team project set, so that you know you are missing one project. You don't need to do that yourself with your app project.
